<?php
namespace Apps\Controllers;

use Cygnite\Mvc\Controller\AbstractBaseController;

/**
 * This file is generated by Cygnite CLI
 * You may alter code to fit your needs
 */

class ViewerController extends AbstractBaseController
{
    protected $layout = 'layout.viewerjs';

    protected $templateEngine = false;

    /**
     * Your constructor.
     *
     * @access public
     *
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * Default Action
     */
    public function indexAction()
    {
        $this->render( 'index', [ 'title' => 'viewerJS' ] );
    }

}