<?php
namespace Apps\Models;

use Cygnite\Foundation\Application;
use Cygnite\Database\Schema;
use Cygnite\Common\UrlManager\Url;
use Cygnite\Database\ActiveRecord;

/**
* This file is generated by Cygnite CLI Crud generator
*/

class Files extends ActiveRecord
{
    //your database connection name
    // protected $database = 'cygnite';

    /*
     | By default Every model class name used as table name
     | "User" => 'user'
     | You can also override the table name here
     */
    protected $tableName = 'files';

    protected $primaryKey = 'files_id';

    //public $perPage = 5;

    public function __construct()
    {
        parent::__construct();
    }

    public function getLastId()
    {
        $files = Files::last();
        $data  = $files->offsetGet(0);
        return $data->files_id;
    }

    /*
    // used for pagination
    public function pageLimit()
    {
        return Url::segment(3);
    }
    */

    /**
     * Skip columns from the select query
     * @return array
     */
    public function skip()
    {
        return array('created_at', 'updated_at');
    }

    public function convertFilename( $name ){
        $tmp = explode(".", $name );
        $ext = array_pop( $tmp );
        return base64_encode(join(".", $tmp)) . "." . $ext;
    }
}// End of the User Model