<?php
namespace Apps\Models;

use Cygnite\Foundation\Application;
use Cygnite\Database\Schema;
use Cygnite\Common\UrlManager\Url;
use Cygnite\Database\ActiveRecord;

/**
* This file is generated by Cygnite CLI Crud generator
*/

class Logs extends ActiveRecord
{
    //your database connection name
    // protected $database = 'cygnite';

    /*
     | By default Every model class name used as table name
     | "User" => 'user'
     | You can also override the table name here
     */
    protected $tableName = 'logs';

    protected $primaryKey = 'logs_id';

    //public $perPage = 5;

    public function __construct()
    {
        parent::__construct();
    }

    public function add($type, $userInfo, $message='')
    {
    	// show($userInfo);exit;
    	if( !$message ){
    		switch( $type ){
    			case 'login':
    				$message = $userInfo['firstname'] . ' ' . $userInfo['lastname'];
    			break;
    		}
    	}
    	$logs = new Logs();
    	$logs->message = (string) $message;
    	$logs->user_id = (int) $userInfo['user_id'];
    	$logs->logs_type = $type;
    	$logs->save();
    }

    public function getLogs($type, $option=array())
    {
    	$sql  = "select logs.*,firstname,lastname from logs join user using(user_id) where logs_type='".$type."' order by ts desc limit 5";
    	$data = $this->query( $sql )->getAll(\PDO::FETCH_ASSOC);
    	return $data;
    }

    /*
    // used for pagination
    public function pageLimit()
    {
        return Url::segment(3);
    }
    */

    /**
     * Skip columns from the select query
     * @return array
     */
    public function skip()
    {
        return array('created_at', 'updated_at');
    }
}// End of the User Model